name: Build, Lint & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Run Rust tests
        run: make test
      - name: Publish to crates.io
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
